# Generated by Django 3.0.2 on 2020-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64, verbose_name='사용자명')),
                ('passWord', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('signUpDateTime', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
            ],
            options={
                'db_table': 'alice_aliceUser',
            },
        ),
    ]
