# Generated by Django 3.0.2 on 2020-02-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='signUpDateTime',
            new_name='registerDateTime',
        ),
    ]
